plugins {
    id 'com.android.application'
}

import groovy.json.JsonSlurper

def versionFile = file('../version.json')
def appVersionName = "1.0.0"
def appVersionCode = 1
if (versionFile.exists()) {
    def json = new JsonSlurper().parseText(versionFile.text)
    appVersionName = json.version

    // แปลงเลขเวอร์ชัน (เช่น "1.2.3") เป็น versionCode (เช่น 10203)
    def parts = appVersionName.tokenize('.')
    if (parts.size() >= 3) {
        appVersionCode = (parts[0].toInteger() * 10000) + (parts[1].toInteger() * 100) + parts[2].toInteger()
    }
}

android {
    namespace 'com.towerdefense.infinity'
    compileSdk 33

    defaultConfig {
        applicationId "com.towerdefense.infinity"
        minSdk 21
        targetSdk 33
        versionCode appVersionCode
        versionName appVersionName

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    
    // Library สำหรับเช็คอัปเดตจาก GitHub
    implementation 'com.github.javiersantos:AppUpdater:2.7'
}
